### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by maximusblade** [DraperStudio/Laravel-Reportable#1]
Nice to have:

- List all reported models
- List reported models filtered by * (concluded Only, Unconcluded, etc)
- Remove All reports from Model
- Remove unconcluded reports from Model
- Added multiple status for report ("unconcluded", "in review", "denied" etc )

**Comment by DraperStudio** [comment]
The `reports` method returns a `morphMany` relationship so you can just call any Elouquent methods on those.

Might add helper methods one day, but not for now.
